"""Access administration of one tenant: workspaces, users, memberships, connections and capability grants.

Rules (every one is tested), on top of those in admin.py (active owner/admin, live check, tenant scope, audit in the
same transaction):
- ROLE CEILING: nobody grants, changes or removes a role higher than their own. An admin can make members, viewers and
  other admins; only an owner makes an owner. A membership above the actor's role cannot be touched at all.
- NO SELF-LOCKOUT / NO SELF-ESCALATION: you cannot change your own role, deactivate your own membership or change your own
  user's status. The last active owner of a tenant cannot be demoted or deactivated.
- GRANTS: only for capabilities that exist and are PRODUCTION_ENABLED, only to an ACTIVE user with an ACTIVE membership in
  the workspace; delete and irreversible capabilities can be granted only by an owner. Granting is immediate (S8 reads
  grants live); revoking is immediate.
- IDs are generated by the server (user, membership, connection and grant ids are global keys).
- Removing access does not delete anything: memberships, connections and grants are deactivated; users get a status.
"""
from __future__ import annotations

import json
import re
import uuid
from datetime import datetime

from adapters.postgres.admin import RANK, Actor, AdminError, AdminService

USER_STATUSES = ("active", "inactive", "suspended", "deactivated", "revoked", "deleted")
ROLES = tuple(RANK)
_HIGH_IMPACT = frozenset({"D", "IRREVERSIBLE"})
MAX_NAME = 100


def _new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


def _name(value: str | None, field: str = "name") -> str | None:
    if value is None:
        return None
    if not value.strip() or len(value) > MAX_NAME or re.search(r"[\x00-\x1f\x7f]", value):
        raise AdminError(422, f"{field}_invalid")
    return value


class AccessAdmin:
    def __init__(self, admin: AdminService) -> None:
        self._a = admin
        self._db = admin._db

    def _tx(self, actor: Actor):
        return self._db.tenant_transaction(actor.principal.tenant_id)

    # ---- helpers ---------------------------------------------------------------------------------

    async def _top_role(self, c, actor: Actor, user_id: str) -> int:
        """The highest role rank among the user's ACTIVE memberships (-1 if none)."""
        rows = await c.fetch("SELECT role FROM memberships WHERE tenant_id = $1 AND user_id = $2 AND is_active"
                             " AND revoked_at IS NULL", actor.principal.tenant_id, user_id)
        return max((RANK[r["role"]] for r in rows), default=-1)

    def _may_touch(self, actor: Actor, rank: int) -> None:
        if rank > RANK[actor.role]:
            raise AdminError(403, "role_exceeds_yours")

    async def _membership(self, c, actor: Actor, membership_id: str) -> dict:
        m = await c.fetchrow("SELECT membership_id, user_id, workspace_id, role, is_active, revoked_at FROM memberships"
                             " WHERE membership_id = $1 AND tenant_id = $2 FOR UPDATE",
                             membership_id, actor.principal.tenant_id)
        if m is None:
            raise AdminError(404, "membership_not_found")
        return dict(m)

    async def _active_owners(self, c, actor: Actor, excluding: str | None = None) -> int:
        return await c.fetchval(
            "SELECT count(DISTINCT user_id) FROM memberships WHERE tenant_id = $1 AND role = 'owner' AND is_active"
            " AND revoked_at IS NULL AND ($2::text IS NULL OR membership_id <> $2)", actor.principal.tenant_id, excluding)

    async def _user(self, c, actor: Actor, user_id: str) -> dict:
        u = await c.fetchrow("SELECT user_id, status, is_service FROM users WHERE user_id = $1 AND tenant_id = $2 FOR UPDATE",
                             user_id, actor.principal.tenant_id)
        if u is None:
            raise AdminError(404, "user_not_found")
        return dict(u)

    async def _workspace(self, c, actor: Actor, workspace_id: str) -> None:
        if await c.fetchval("SELECT 1 FROM workspaces WHERE workspace_id = $1 AND tenant_id = $2",
                            workspace_id, actor.principal.tenant_id) is None:
            raise AdminError(404, "workspace_not_found")

    # ---- workspaces ------------------------------------------------------------------------------

    async def create_workspace(self, actor: Actor, name: str) -> str:
        name = _name(name)
        workspace_id = _new_id("ws")
        async with self._tx(actor) as c:
            await c.execute("INSERT INTO workspaces (workspace_id, tenant_id, name, created_by) VALUES ($1,$2,$3,$4)",
                            workspace_id, actor.principal.tenant_id, name, actor.principal.user_id)
            await self._a._audit(c, actor, "workspace.create", "workspace", workspace_id, name=name)
        return workspace_id

    async def list_workspaces(self, actor: Actor) -> list[dict]:
        async with self._tx(actor) as c:
            rows = await c.fetch("SELECT workspace_id, name, paused_until, scheduled_activation_at, created_by, created_at"
                                 " FROM workspaces WHERE tenant_id = $1 ORDER BY created_at, workspace_id",
                                 actor.principal.tenant_id)
        return [dict(r) for r in rows]

    # ---- users -----------------------------------------------------------------------------------

    async def create_user(self, actor: Actor, display_name: str | None = None, is_service: bool = False) -> str:
        """A user with no memberships (and so no access) until a membership is added."""
        display_name = _name(display_name, "display_name")
        user_id = _new_id("usr")
        async with self._tx(actor) as c:
            await c.execute("INSERT INTO users (user_id, tenant_id, display_name, is_service, created_by)"
                            " VALUES ($1,$2,$3,$4,$5)", user_id, actor.principal.tenant_id, display_name, is_service,
                            actor.principal.user_id)
            await self._a._audit(c, actor, "user.create", "user", user_id, display_name=display_name, is_service=is_service)
        return user_id

    async def list_users(self, actor: Actor) -> list[dict]:
        async with self._tx(actor) as c:
            rows = await c.fetch(
                "SELECT u.user_id, u.display_name, u.status, u.is_service, u.created_by, u.created_at,"
                " COALESCE(json_agg(json_build_object('membership_id', m.membership_id, 'workspace_id', m.workspace_id,"
                " 'role', m.role, 'active', m.is_active AND m.revoked_at IS NULL) ORDER BY m.membership_id)"
                " FILTER (WHERE m.membership_id IS NOT NULL), '[]') AS memberships"
                " FROM users u LEFT JOIN memberships m ON m.user_id = u.user_id AND m.tenant_id = u.tenant_id"
                " WHERE u.tenant_id = $1 GROUP BY u.user_id ORDER BY u.created_at, u.user_id", actor.principal.tenant_id)
        return [{**dict(r), "memberships": json.loads(r["memberships"])} for r in rows]

    async def set_user_status(self, actor: Actor, user_id: str, status: str) -> None:
        if status not in USER_STATUSES:
            raise AdminError(422, "status_invalid")
        if user_id == actor.principal.user_id:
            raise AdminError(403, "cannot_change_yourself")
        async with self._tx(actor) as c:
            user = await self._user(c, actor, user_id)
            self._may_touch(actor, await self._top_role(c, actor, user_id))
            if status != "active" and await self._would_orphan_owner(c, actor, user_id):
                raise AdminError(409, "last_owner")
            await c.execute("UPDATE users SET status = $2 WHERE user_id = $1 AND tenant_id = $3", user_id, status,
                            actor.principal.tenant_id)
            await self._a._audit(c, actor, "user.status", "user", user_id, status=status, previous=user["status"])

    async def _would_orphan_owner(self, c, actor: Actor, user_id: str) -> bool:
        """True if deactivating this user would leave the tenant without an active owner."""
        is_owner = await c.fetchval("SELECT EXISTS (SELECT 1 FROM memberships WHERE tenant_id = $1 AND user_id = $2"
                                    " AND role = 'owner' AND is_active AND revoked_at IS NULL)", actor.principal.tenant_id, user_id)
        if not is_owner:
            return False
        others = await c.fetchval("SELECT count(DISTINCT m.user_id) FROM memberships m JOIN users u ON u.user_id = m.user_id"
                                  " WHERE m.tenant_id = $1 AND m.role = 'owner' AND m.is_active AND m.revoked_at IS NULL"
                                  " AND m.user_id <> $2 AND u.status = 'active'", actor.principal.tenant_id, user_id)
        return others == 0

    # ---- memberships -----------------------------------------------------------------------------

    async def add_membership(self, actor: Actor, user_id: str, workspace_id: str, role: str) -> str:
        if role not in ROLES:
            raise AdminError(422, "role_invalid")
        self._may_touch(actor, RANK[role])
        async with self._tx(actor) as c:
            user = await self._user(c, actor, user_id)
            await self._workspace(c, actor, workspace_id)
            self._may_touch(actor, await self._top_role(c, actor, user_id))       # cannot reshape a higher user's access
            if user["status"] != "active":
                raise AdminError(409, "user_inactive")
            membership_id = _new_id("mem")
            try:
                await c.execute("INSERT INTO memberships (membership_id, tenant_id, user_id, workspace_id, role, created_by)"
                                " VALUES ($1,$2,$3,$4,$5,$6)", membership_id, actor.principal.tenant_id, user_id,
                                workspace_id, role, actor.principal.user_id)
            except Exception as exc:  # noqa: BLE001 — the unique (tenant, user, workspace) constraint
                if "memberships_tenant_id_user_id_workspace_id_key" in str(exc) or "unique" in str(exc).lower():
                    raise AdminError(409, "membership_exists") from None
                raise
            await self._a._audit(c, actor, "membership.add", "membership", membership_id, user_id=user_id,
                                 workspace_id=workspace_id, role=role)
        return membership_id

    async def list_memberships(self, actor: Actor, user_id: str | None = None) -> list[dict]:
        async with self._tx(actor) as c:
            rows = await c.fetch("SELECT membership_id, user_id, workspace_id, role, is_active, revoked_at, created_by, created_at"
                                 " FROM memberships WHERE tenant_id = $1 AND ($2::text IS NULL OR user_id = $2)"
                                 " ORDER BY created_at, membership_id", actor.principal.tenant_id, user_id)
        return [dict(r) for r in rows]

    async def set_role(self, actor: Actor, membership_id: str, role: str) -> None:
        if role not in ROLES:
            raise AdminError(422, "role_invalid")
        async with self._tx(actor) as c:
            m = await self._membership(c, actor, membership_id)
            if m["user_id"] == actor.principal.user_id:
                raise AdminError(403, "cannot_change_yourself")
            self._may_touch(actor, RANK[m["role"]])
            self._may_touch(actor, RANK[role])
            if not m["is_active"] or m["revoked_at"] is not None:
                raise AdminError(409, "membership_inactive")
            if m["role"] == "owner" and role != "owner" and await self._active_owners(c, actor, excluding=membership_id) == 0:
                raise AdminError(409, "last_owner")
            await c.execute("UPDATE memberships SET role = $2 WHERE membership_id = $1", membership_id, role)
            await self._a._audit(c, actor, "membership.role", "membership", membership_id, previous=m["role"], role=role)

    async def remove_membership(self, actor: Actor, membership_id: str) -> None:
        """Deactivate (the row stays for the record); the holder loses access to the workspace at once."""
        async with self._tx(actor) as c:
            m = await self._membership(c, actor, membership_id)
            if m["user_id"] == actor.principal.user_id:
                raise AdminError(403, "cannot_change_yourself")
            self._may_touch(actor, RANK[m["role"]])
            if not m["is_active"] or m["revoked_at"] is not None:
                raise AdminError(404, "membership_not_found")
            if m["role"] == "owner" and await self._active_owners(c, actor, excluding=membership_id) == 0:
                raise AdminError(409, "last_owner")
            await c.execute("UPDATE memberships SET is_active = false, revoked_at = now() WHERE membership_id = $1",
                            membership_id)
            await self._a._audit(c, actor, "membership.remove", "membership", membership_id, user_id=m["user_id"])

    # ---- connections -----------------------------------------------------------------------------

    async def create_connection(self, actor: Actor, user_id: str, workspace_id: str,
                                expires_at: datetime | None = None) -> str:
        """A connection for a user who has an ACTIVE membership in the workspace."""
        async with self._tx(actor) as c:
            user = await self._user(c, actor, user_id)
            if user["status"] != "active":
                raise AdminError(409, "user_inactive")
            m = await c.fetchrow("SELECT role FROM memberships WHERE tenant_id = $1 AND user_id = $2 AND workspace_id = $3"
                                 " AND is_active AND revoked_at IS NULL", actor.principal.tenant_id, user_id, workspace_id)
            if m is None:
                raise AdminError(409, "no_active_membership")
            self._may_touch(actor, RANK[m["role"]])
            if expires_at is not None and (expires_at.tzinfo is None or expires_at <= await c.fetchval("SELECT now()")):
                raise AdminError(422, "expires_at_invalid")
            connection_id = _new_id("conn")
            await c.execute("INSERT INTO connections (connection_id, tenant_id, user_id, workspace_id, expires_at, created_by)"
                            " VALUES ($1,$2,$3,$4,$5,$6)", connection_id, actor.principal.tenant_id, user_id, workspace_id,
                            expires_at, actor.principal.user_id)
            await self._a._audit(c, actor, "connection.create", "connection", connection_id, user_id=user_id,
                                 workspace_id=workspace_id)
        return connection_id

    async def list_connections(self, actor: Actor, user_id: str | None = None) -> list[dict]:
        async with self._tx(actor) as c:
            rows = await c.fetch("SELECT connection_id, user_id, workspace_id, status, expires_at, created_by, created_at"
                                 " FROM connections WHERE tenant_id = $1 AND ($2::text IS NULL OR user_id = $2)"
                                 " ORDER BY created_at, connection_id", actor.principal.tenant_id, user_id)
        return [dict(r) for r in rows]

    async def revoke_connection(self, actor: Actor, connection_id: str) -> None:
        async with self._tx(actor) as c:
            conn = await c.fetchrow("SELECT user_id, status FROM connections WHERE connection_id = $1 AND tenant_id = $2"
                                    " FOR UPDATE", connection_id, actor.principal.tenant_id)
            if conn is None or conn["status"] == "revoked":
                raise AdminError(404, "connection_not_found")
            self._may_touch(actor, await self._top_role(c, actor, conn["user_id"]))
            await c.execute("UPDATE connections SET status = 'revoked' WHERE connection_id = $1", connection_id)
            await self._a._audit(c, actor, "connection.revoke", "connection", connection_id, user_id=conn["user_id"])

    # ---- capabilities and grants -----------------------------------------------------------------

    async def list_capabilities(self, actor: Actor) -> list[dict]:
        async with self._tx(actor) as c:
            rows = await c.fetch("SELECT capability_id, name, intent, mutation, risk_floor FROM capabilities"
                                 " WHERE truth_state = 'PRODUCTION_ENABLED' ORDER BY capability_id")
        return [dict(r) for r in rows]

    async def grant(self, actor: Actor, user_id: str, workspace_id: str, capability_id: str,
                    expires_at: datetime | None = None) -> str:
        async with self._tx(actor) as c:
            user = await self._user(c, actor, user_id)
            await self._workspace(c, actor, workspace_id)
            if user["status"] != "active":
                raise AdminError(409, "user_inactive")
            m = await c.fetchrow("SELECT role FROM memberships WHERE tenant_id = $1 AND user_id = $2 AND workspace_id = $3"
                                 " AND is_active AND revoked_at IS NULL", actor.principal.tenant_id, user_id, workspace_id)
            if m is None:
                raise AdminError(409, "no_active_membership")
            self._may_touch(actor, RANK[m["role"]])
            cap = await c.fetchrow("SELECT mutation FROM capabilities WHERE capability_id = $1 AND truth_state = 'PRODUCTION_ENABLED'",
                                   capability_id)
            if cap is None:
                raise AdminError(404, "capability_not_found")
            if cap["mutation"] in _HIGH_IMPACT and actor.role != "owner":
                raise AdminError(403, "owner_required_for_high_impact")
            if expires_at is not None and (expires_at.tzinfo is None or expires_at <= await c.fetchval("SELECT now()")):
                raise AdminError(422, "expires_at_invalid")
            if await c.fetchval("SELECT 1 FROM capability_grants WHERE tenant_id = $1 AND user_id = $2 AND workspace_id = $3"
                                " AND capability_id = $4 AND is_active AND (expires_at IS NULL OR expires_at > now())",
                                actor.principal.tenant_id, user_id, workspace_id, capability_id):
                raise AdminError(409, "grant_exists")
            grant_id = _new_id("grant")
            await c.execute("INSERT INTO capability_grants (capability_grant_id, tenant_id, workspace_id, user_id, capability_id,"
                            " is_active, expires_at, created_by) VALUES ($1,$2,$3,$4,$5,true,$6,$7)", grant_id,
                            actor.principal.tenant_id, workspace_id, user_id, capability_id, expires_at, actor.principal.user_id)
            await self._a._audit(c, actor, "grant.create", "grant", grant_id, user_id=user_id, workspace_id=workspace_id,
                                 capability_id=capability_id, mutation=cap["mutation"])
        return grant_id

    async def list_grants(self, actor: Actor, user_id: str | None = None) -> list[dict]:
        async with self._tx(actor) as c:
            rows = await c.fetch("SELECT capability_grant_id AS grant_id, user_id, workspace_id, capability_id, is_active,"
                                 " expires_at, created_by, created_at FROM capability_grants WHERE tenant_id = $1"
                                 " AND ($2::text IS NULL OR user_id = $2) ORDER BY created_at, capability_grant_id",
                                 actor.principal.tenant_id, user_id)
        return [dict(r) for r in rows]

    async def revoke_grant(self, actor: Actor, grant_id: str) -> None:
        async with self._tx(actor) as c:
            g = await c.fetchrow("SELECT user_id, capability_id FROM capability_grants WHERE capability_grant_id = $1"
                                 " AND tenant_id = $2 AND is_active FOR UPDATE", grant_id, actor.principal.tenant_id)
            if g is None:
                raise AdminError(404, "grant_not_found")
            self._may_touch(actor, await self._top_role(c, actor, g["user_id"]))
            await c.execute("UPDATE capability_grants SET is_active = false WHERE capability_grant_id = $1", grant_id)
            await self._a._audit(c, actor, "grant.revoke", "grant", grant_id, user_id=g["user_id"],
                                 capability_id=g["capability_id"])
