"""EventEnvelope (DATA_CONTRACTS §46): an externally triggered event, created only by the gateway.

`tenant_id` and `workspace_id` come from the gateway's authentication (the signing-secret
lookup), NEVER from the payload (invariant I-022).
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class EventEnvelope:
    event_id: str                    # UUID v4, generated by the gateway
    correlation_id: str              # UUID v4, generated by the gateway; S0 uses it as conversation_id
    source: str                      # "webhook" | "mcp" | "api" | "schedule"
    source_system: str               # "ghl" | "stripe" | "custom" | "mcp"
    type: str                        # event type, validated shape
    payload_ref: str                 # "pg:event_log.<event_id>"
    payload_checksum: str            # SHA-256 (hex) of the raw body
    tenant_id: str                   # from authentication
    workspace_id: str                # from authentication
    timestamp: str                   # ISO 8601 UTC (signed timestamp, or planned fire time, or receipt time)
    metadata: dict = field(default_factory=dict)
    schema_version: str = "1"        # version of the registered payload schema the payload satisfied
